### ISSUE TITLE
Rename again

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/screenplay.js#31]
The current new name is bound to create the false impression that this integrates with https://github.com/microsoft/playwright

I’ll rename to dollshouse next week as I suggested in #25 - unless someone convinces me of a better name first.

/cc @mattwynne @vincent-psarga

**Comment by mattwynne** [comment]
Ugh. Shame. I really like "playwright".

Why dollshouse? What's the metaphor?

Other ideas:

- screenplay-lite
- action-stations
- ...

Honestly, I disagree with @jan-molak's assertion in #25 that this isn't faithful enough to the screenplay pattern to share the same name. I think it's close enough to be relevant and easily found from a search query. The differences are interesteding and perhaps just reflect an evolution of the pattern. Certainly I think what we've done here with polymorphism for interactions is really important work.

Also, I think we _should_ add Tasks to this library, because they're awesome.

I'd be interested in @wakaleo / @antonymarcano / @andypalmer's takes on this.

**Comment by jan-molak** [comment]
Hey @mattwynne - it feels like the main focus of this library is to build on and expand on @aslakhellesoy's earlier work on [sub-second TDD](https://github.com/subsecondtdd/todo-subsecond) and make multi-layer testing easier thanks to polymorphism. I agree with you that this work is important and valuable.

However, I still stand by my opinion that this pattern is significantly different from the Screenplay Pattern, which has five components (Actors, Abilities, Interactions, Tasks and Question), all serving a [specific purpose](https://serenity-js.org/handbook/thinking-in-serenity-js/screenplay-pattern.html), and is primarily focused on modelling multi-actor workflows.

In this implementation, there are no _abilities_, no _tasks_, and _questions_ and _interactions_ are interchangeable.
Furthermore, I'd argue that by dropping _abilities_ actors become a simple representation of _state_, so you could actually get away without them too.

So reducing the original model this way we'd left with _interactions_ and a polymorphic loading mechanism (which is awesome, by the way).

If we added _tasks_ to this mix, we'd arrive at one of @antonymarcano's earlier models of [Goals, Tasks, Actions](http://antonymarcano.com/blog/2011/03/goals-tasks-action/).

So perhaps it would make sense to focus this library on _actions_, and making them polymorphic, and call it say `@cucumber/actions`?

**Comment by aslakhellesoy** [comment]
> Why dollshouse? What's the metaphor?

It's a play by playwright Henrik Ibsen and [one of the most played plays ever](https://en.wikipedia.org/wiki/A_Doll%27s_House). It is also regarded as a [great contribution to feminist literature](http://www.beytulhikme.org/Makaleler/1429140981_03_Balaky_(31-45).pdf).

For people who don't know the play, I think "doll's house" would invoke associations of multiple actors (that's what you typically find in kids' dolls houses). We could emphasise this with a logo picturing multiple characters in a house (or a cage, as has been used for theatre posters).

And most importantly - I think libraries with original names are more fun - "screenplay" is a bit dull IMHO :-)

> Honestly, I disagree with @jan-molak's assertion in #25 that this isn't faithful enough to the screenplay pattern to share the same name. I think it's close enough to be relevant and easily found from a search query. 

Ok, let's revisit that discussion.

*Abilities*

I said previously that playwright doesn't implement them. What I meant is that it doesn't implement them as an *actor has abilities* OO relationship. However, you could argue that the polymorphic interactions described [here](https://github.com/cucumber/playwright.js#using-different-interaction-implementations) and implemented [here](https://github.com/cucumber/playwright.js/blob/1ebc32729f475c9af672395e821224da8fe1d05a/src/ActorWorld.ts#L12) is just a different implementation of abilities that achieve the same goal. The main difference is that deciding what abilities are available is done in configuration (world parameters) rather than in code.

*Tasks*

In fact, I think what we currently call *interactions* in this library should be renamed to *tasks*. I also think that the decomposition of tasks into interactions is something the library doesn't need an API for. It's just delegation/extract method, and could be handled by user code.

*Questions*

They are supported through the `Actor#ask` method.

> Also, I think we should add Tasks to this library, because they're awesome.

See my comment above. Screenplay is a *pattern*, and it is not prescriptive of what parts of the pattern should be implemented in a library, and what should be implemented in user code. I believe decomposing tasks into interactions can be handled by user code and still be faithful to the pattern.

**Comment by wakaleo** [comment]
I would say that the actors, tasks, questions and abilities are pretty central to the DNA of the Screenplay pattern. What you are describing sounds more like what I called Action Classes in https://johnfergusonsmart.com/page-objects-that-suck-less-tips-for-writing-more-maintainable-page-objects/, and App Actions in Cypress. I agree with Jan in that, which there are similarities with the Screenplay pattern, without the activities and questions it really feels like it's own thing. 

A rendering library could be used as part of an implementation of an MVC pattern, but in itself it does not implement the pattern. The other Screenplay implementations out there, such as the .NET (https://automationpanda.com/2020/10/16/introducing-boa-constrictor-the-net-screenplay-pattern/) and Python (https://screenpy-docs.readthedocs.io/en/latest/) respect the Actors/Abilities/Tasks/Interactions/Questions architecture pretty rigorously.

**Comment by antonymarcano** [comment]
I don't agree that the fully-fledged implementation is entirely necessary in all cases.
I would say, in its purest state, it's about Actors and Tasks... Here, when you read Task, think **_the what_** – e.g. "Make a call". When you read Actions, think **_the how_** – e.g. "unlock phone, open contacts, enter 'Aslak' into the search box... etc). 

Everything else is just options. Actions can just be imperative lines of code doing things. Questions were just a way to have fluent assertions using a Given/When/Then style in code and due to the constraints of Java largely. I'm not sure that's as relevant with Cucumber (or javascript).

If I need to have a return type for a `Task`, that would be an `Outcome` – something you can use to return state (or not).

When I relate this to Cucumber, I explain it something like this:
**Goals**: the Scenario title is written as the user's goal (e.g. `Scenario: Get feedback on why my email was invalid`)
  -> **Tasks**: Steps say '**_what_**' the actor is doing (and the Step Def acts as a thin adapter delegating to a `Task`)
    --> **Actions**: are the '**_how_**' concrete things an actor would do – think 'interactions' – one of more of which will be inside the body of a Task. This could just be imperative lines of code, or that too can be abstracted behind the concept of an Action... Hence, the Actor and Task is the more important concept.

The pattern was intended to break the structural thinking binding people to a 'page' concept (which continued long after the concept of a page in web apps became irrelevant) and to do the same for APIs – enabling what [I demonstrated in 2012](https://skillsmatter.com/skillscasts/3141-user-centred-scenarios-describing-capabilities-not-solutions) – [the code for which is here](https://skillsmatter.com/skillscasts/3141-user-centred-scenarios-describing-capabilities-not-solutions).

Instead, I wanted to encourage people to model the domain – that there are people using our products to complete tasks (like "Pay by Card") that each involve one or more actions. The benefits of the resulting abstractions will be clear to this group.

I encourage you to consider thinking of the Actor performing Tasks... and to feel free to continue the exploration of the ideas inspired by Screenplay – under the same name if you would like to... Or under another name if you prefer.

**Comment by aurelien-reeves** [comment]
I think @cucumber/dollshouse is fine.
I have also the following suggestion: @cucumber/scene. As this is where actors play their parts.

**Comment by mattwynne** [comment]
I like those suggestions @aurelien-reeves. `@cucumber/stageplay`?

**Comment by mattwynne** [comment]
But, having now read @antonymarcano's reply I suggest we rename what we've called "interactions" to "tasks", and then keep the name screenplay. I think I'd misunderstood the distinction between those two a little bit.

I can imagine that this library might evolve to support these other concepts as the need for them becomes clearer.

I'm super curious about how we can fit the polymorphism concept into the screenplay metaphor. I'd personally called these _Perspectives_ in a [previous iteration](https://github.com/cucumber-ltd/feynmanl) of this idea, my thinking being that Actors carry out their Actions through a Perspective.

I have to admit I never really understood Abilities, so not sure where they would fit into this idea.

**Comment by antonymarcano** [comment]
Abilities came about to separate the actions from the means of achieving
them. This is one way to create the option to polymorphically substitute
the means by which you interact with the product without having to have
multiple implementations of tasks.

**Comment by aslakhellesoy** [comment]
> But, having now read @antonymarcano's reply I suggest we rename what we've called "interactions" to "tasks", and then keep the name screenplay. I think I'd misunderstood the distinction between those two a little bit.

I agree.

Decomposing a task into multiple interactions is something I don't think the library needs to provide an API for. It's just an extract method refactoring. It's a concept of the pattern that doesn't need to be implemented in a library. The programming language provides the constructs you need.

**Comment by aslakhellesoy** [comment]
I've addressed the renames in #34

Here is an [example of a task](https://github.com/cucumber/playwright.js/blob/rename-interactions-to-tasks/features/support/tasks/dom/shout.ts) that is decomposed into interactions.

**Comment by aslakhellesoy** [comment]
Now that #34 illustrates the following:

* Actors
* Tasks
* Questions
* Interactions (aka Actions)
* Abilities (implemented as dynamic loading of polymorphic task implementations)

...do we have your blessing to rename this back to `@cucumber/screenplay` @antonymarcano?

(BTW, I have updated the [credits](https://github.com/cucumber/playwright.js/blob/main/README.md#credits) section with more historical links dating back to 2007).

**Comment by aslakhellesoy** [comment]
🥺 @antonymarcano 🥺

**Comment by aslakhellesoy** [comment]
@mattwynne I think we should rename it back to `@cucumber/screenplay.js` since Antony hasn't objected. The playwright name is already causing confusion:

* https://cucumberbdd.slack.com/archives/C6QJ6N695/p1627387307165100
* https://twitter.com/TallyBarak/status/1359365413092605952

I'm on holiday for another few weeks - do you have time to do this in the meanwhile?

**Comment by mattwynne** [comment]
Done! Bon vaccances @aslakhellesoy! 🏖️

**Comment by aslakhellesoy** [comment]
Thanks 😊 

I’m reopening this since it’s not done yet. Left to do:

- [ ] Rename module in package.json
- [ ] Undeprecate the deprecated `@cucumber/screenplay` module on npm
- [ ] Deprecate `@cucumber/playwright` on npm
- [ ] Rename any mentions in code and docs
- [ ] Make a new release as `@cucumber/screenplay`

**Comment by aurelien-reeves** [comment]
Just noticed that I am still not part of the @cucumber organization on npmjs.com.
Could I be invited? That way I could make some progress with that issue

Also, how do we deprecate things on NPM? Is it just some mentions in the README?

**Comment by aslakhellesoy** [comment]
> Just noticed that I am still not part of the @cucumber organization on npmjs.com.

You don't need to be. Use the `cukebot` account - credentials are in the keybase secret repo.

> Also, how do we deprecate things on NPM?

Google it :-) https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by aurelien-reeves** [comment]
> 
> 
> > Just noticed that I am still not part of the @cucumber organization on npmjs.com.
> 
> You don't need to be. Use the `cukebot` account - credentials are in the keybase secret repo.
> 

👍 thanks

> > Also, how do we deprecate things on NPM?
> 
> Google it :-) https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

😶 Yes, of course. Sorry :(

**Comment by aurelien-reeves** [comment]
"Rename any mentions in code and docs"

Is there any other doc than the README?

**Comment by aslakhellesoy** [comment]
Great! Thanks for doing this. The README.md is the only docs btw

**Comment by aslakhellesoy** [comment]
There is an open PR - would be good to get that merged before doing a release.

**Comment by aurelien-reeves** [comment]
> 
> 
> There is an open PR - would be good to get that merged before doing a release.

Too late :(
